# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
steps:
  - task: Npm@0
    displayName: 'npm install'
    inputs:
      arguments: '--force'

  - task: Npm@1
    displayName: 'npm install angular cli'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install @angular/cli'
  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build --prod'
  - task: ArchiveFiles@1
    displayName: 'Archive files '
    inputs:
      rootFolder: 'dist/TestApp' #name of your project on angular.json .defaultProject value
      includeRootFolder: false
  - task: CopyFiles@2
    displayName: 'Copy File to: $(TargetFolder)'
    inputs:
      SourceFolder: 'dist/TestApp'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: drop'
  - task: S3Upload@1
    displayName: 'Agular APP CD AWS S3' 
    inputs:
      awsCredentials: 'AWS Connection'
      regionName: 'us-east-2'
      bucketName: 'bucket84'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      globExpressions: '**'
  - task: AWSCLI@1
    displayName: 'Cloud Front Create Invalidation' 
    inputs:
      awsCredentials: 'AWS Connection'
      regionName: 'us-east-2'
      awsCommand: 'cloudfront'
      awsSubCommand: 'create-invalidation'
      awsArguments: '--distribution-id E9MGBN3LKYSKI --paths "/*"'
  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy on Azure App Service' 
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1 (6c74c0b1-61b3-44e6-bada-c36d5a1eb330)'
      appType: 'webApp'
      WebAppName: 'TestAngularApp1'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'